apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: microsrvc1mysql
    version: "1.0"
  name: microsrvc1mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microsrvc1mysql
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: microsrvc1mysql
    spec:
      containers:
        - name: microsrvc1mysql
          image: yakerlydia/microsrvc1mysql:1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          resources: { }
status: { }

---

apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: microsrvc1mysql
  name: microsrvc1mysql
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
      name: http
  selector:
    app: microsrvc1mysql
  type: NodePort
status:
  loadBalancer: {}
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway

metadata:
  name: microservice-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*"

---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: microsrvc1mysql
spec:
  hosts:
    - "*"
  gateways:
    - microservice-gateway
  http:
    - match:
        - uri:
            prefix: /microsrvc1mysql/
      rewrite:
        uri: /
      route:
        - destination:
            port:
              number: 80
            host: microsrvc1mysql.default.svc.cluster.local