apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysqlv5
spec:
  selector:
    matchLabels:
      app: mysqlv5
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysqlv5
    spec:
      containers:
        - image: mysql:5.7
          name: mysqlv5

          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: password
            - name: MYSQL_USER
              value: admin
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: password
            - name: MYSQL_TCP_PORT
              value: "3306"
            - name: MYSQL_ROOT_HOST
              value: "%"
          ports:
            - containerPort: 3306
              name: mysqlv5
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
              subPath: my.cnf
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim
