apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: microsrvc2
    version: "1.0"
  name: microsrvc2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microsrvc2
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: microsrvc2
    spec:
      containers:
        - name: microsrvc2
          image: yakerlydia/microsrvc2:1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          resources: { }
status: { }

---

apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: microsrvc2
  name: microsrvc2
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
      name: http
  selector:
    app: microsrvc2
  type: NodePort
status:
  loadBalancer: {}

---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: microsrvc2
spec:
  hosts:
    - "*"
  gateways:
    - microservice-gateway
  http:
    - match:
        - uri:
            prefix: /microsrvc2/
      rewrite:
        uri: /
      route:
        - destination:
            port:
              number: 80
            host: microsrvc2.default.svc.cluster.local